// Generated by wxt
export {}
declare global {
  const ACCESS_CODE_LENGTH: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/constants').ACCESS_CODE_LENGTH
  const COLORS: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/constants').COLORS
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DEFAULT_API_ENDPOINT: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/constants').DEFAULT_API_ENDPOINT
  const DEFAULT_STORAGE: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/types').DEFAULT_STORAGE
  const EXTENSION_NAME: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/constants').EXTENSION_NAME
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const LABELS: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/constants').LABELS
  const MAX_HISTORY_SIZE: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/constants').MAX_HISTORY_SIZE
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const MessageType: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/types').MessageType
  const OVERLAY_ID: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/constants').OVERLAY_ID
  const browser: typeof import('wxt/browser').browser
  const checkUrlWithAPI: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/api.service').checkUrlWithAPI
  const clearHistory: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/history.service').clearHistory
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createOverlay: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/overlay').createOverlay
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getAuthStatus: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/auth.service').getAuthStatus
  const getConfig: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/config.service').getConfig
  const getHistory: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/history.service').getHistory
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isOverlayVisible: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/overlay').isOverlayVisible
  const logout: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/auth.service').logout
  const removeFromHistory: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/history.service').removeFromHistory
  const removeOverlay: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/overlay').removeOverlay
  const requireAuth: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/auth.service').requireAuth
  const resetConfig: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/config.service').resetConfig
  const saveToHistory: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/history.service').saveToHistory
  const setConfig: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/config.service').setConfig
  const showOverlay: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/overlay').showOverlay
  const storage: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/storage').storage
  const useActiveTab: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useActiveTab').default
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useAuth: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useAuth').default
  const useBrowserStorage: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useBrowserStorage').default
  const useBrowserStorageMultiple: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useBrowserStorage').useBrowserStorageMultiple
  const useCallback: typeof import('react').useCallback
  const useCheckUrl: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useCheckUrl').default
  const useCloseTabs: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useCloseTabs').useCloseTabs
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const validateAccessCode: typeof import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/auth.service').validateAccessCode
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { ActiveTab } from 'C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useActiveTab'
  import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useActiveTab')
  // @ts-ignore
  export type { UseAuthResult } from 'C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useAuth'
  import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useAuth')
  // @ts-ignore
  export type { UseCheckUrlResult } from 'C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useCheckUrl'
  import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/hooks/useCheckUrl')
  // @ts-ignore
  export type { AuthStatus } from 'C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/auth.service'
  import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/auth.service')
  // @ts-ignore
  export type { OverlayOptions } from 'C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/overlay'
  import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/overlay')
  // @ts-ignore
  export type { MessageTypeKey, MessageTypeValue, ScanResult, CheckUrlMessage, UrlResultMessage, ShowOverlayMessage, DismissOverlayMessage, GetAuthStatusMessage, ValidateAccessCodeMessage, LogoutMessage, ExtensionMessage, MessageResponse, AuthStatusResponse, CheckUrlResponse, PredictRequest, PredictApiResult, PredictResponse, ApiConfig, StorageSchema, StorageKey } from 'C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/types'
  import('C:/Users/th33r/Desktop/Project/final_project/SEMD/semd-extension/src/utils/types')
}
