// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { default as useActiveTab, ActiveTab } from '../src/hooks/useActiveTab';
  export { default as useAuth, UseAuthResult } from '../src/hooks/useAuth';
  export { default as useBrowserStorage, useBrowserStorageMultiple } from '../src/hooks/useBrowserStorage';
  export { default as useCheckUrl, UseCheckUrlResult } from '../src/hooks/useCheckUrl';
  export { useCloseTabs } from '../src/hooks/useCloseTabs';
  export { checkUrlWithAPI } from '../src/utils/api.service';
  export { getAuthStatus, validateAccessCode, logout, requireAuth, AuthStatus } from '../src/utils/auth.service';
  export { getConfig, setConfig, resetConfig } from '../src/utils/config.service';
  export { DEFAULT_API_ENDPOINT, EXTENSION_NAME, MAX_HISTORY_SIZE, ACCESS_CODE_LENGTH, OVERLAY_ID, LABELS, COLORS } from '../src/utils/constants';
  export { saveToHistory, getHistory, clearHistory, removeFromHistory } from '../src/utils/history.service';
  export { createOverlay, showOverlay, removeOverlay, isOverlayVisible, OverlayOptions } from '../src/utils/overlay';
  export { storage } from '../src/utils/storage';
  export { MessageType, DEFAULT_STORAGE, MessageTypeKey, MessageTypeValue, ScanResult, CheckUrlMessage, UrlResultMessage, ShowOverlayMessage, DismissOverlayMessage, GetAuthStatusMessage, ValidateAccessCodeMessage, LogoutMessage, ExtensionMessage, MessageResponse, AuthStatusResponse, CheckUrlResponse, PredictRequest, PredictApiResult, PredictResponse, ApiConfig, StorageSchema, StorageKey } from '../src/utils/types';
}
